/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

import com.openfaas.function.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Handler sut = new Handler();
        assertTrue("Not null", sut!=null);
    }
}
