/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

import com.openfaas.model.IHandler;

import com.openfaas.model.Response;

public class ResponseTest {
    @Test public void testResponseHeaderSetGetValue() {
       Response r = new Response();

       r.setHeader("X-Key", "value");

       assertEquals("value", r.getHeader("X-Key"));
    }

    @Test public void testResponseHeaderGetValueKeyMissIsNull() {
       Response r = new Response();
       assertEquals(null, r.getHeader("No-Such-Key"));
    }

    @Test public void testResponseHeaderSetGetClearGetValue() {
       Response r = new Response();

       r.setHeader("X-Key", "value");
       r.setHeader("X-Key", null);

       assertEquals(null, r.getHeader("X-Key"));
    }
}
